name: GrowingOre
main: net.gamesketch.bukkit.bot.growingore.core
version: 0.0.1
website: http://www.gamesketch.net
author: The GameSketch Community
description: >
             Makes specific ores respawn.
commands: